### ISSUE TITLE
New IANA gem: iana-data

### ISSUE THREAD

**Issue by ringe** [ressy/iana#1]
I cloned your repository, made the adjustments I needed right now and published it on rubygems.org under a new name: iana-data

See https://github.com/ringe/iana
And https://rubygems.org/gems/iana-data

FYI

**Comment by ressy** [comment]
Nice!  I'm glad that ended up being useful for someone.  I'd considered removing it a while back since I hadn't touched the code in so long, but didn't want the original author's work to be lost too (and he'd removed the upstream repo).  I just merged your changes here.  Thanks.

**Comment by ringe** [comment]
Alright! Would you like me to add you as owner at rubygems.org as well?

**Comment by ressy** [comment]
Sorry for the late reply.  No, that's OK, it should probably just be you as far as rubygems.org is concerned; I haven't done active ruby development for a while at this point, and haven't dealt with packaging gems before, anyway.  Maybe Ramsey would be interested, though.  Thanks for the thought.
